In [1]:
import numpy as np
import pandas as pd
import seaborn as ans
import matplotlib.pyplot as plt

In [3]:
df = pd.read_csv('diabetes.csv')

In [4]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0              6      148             72             35        0  33.6   
1              1       85             66             29        0  26.6   
2              8      183             64              0        0  23.3   
3              1       89             66             23       94  28.1   
4              0      137             40             35      168  43.1   
..           ...      ...            ...            ...      ...   ...   
763           10      101             76             48      180  32.9   
764            2      122             70             27        0  36.8   
765            5      121             72             23      112  26.2   
766            1      126             60              0        0  30.1   
767            1       93             70             31        0  30.4   

     DiabetesPedigreeFunction  Age  Outcome  
0                       0.627   50        1  
1                       0.351   31        0  
2                       0.672   32        1  
3                       0.167   21        0  
4                       2.288   33        1  
..                        ...  ...      ...  
763                     0.171   63        0  
764                     0.340   27        0  
765                     0.245   30        0  
766                     0.349   47        1  
767                     0.315   23        0  

[768 rows x 9 columns]

In [5]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_scoreuracy_score

In [6]:
df = df.sample(frac=1)

In [7]:
df

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
362            5      103            108             37        0  39.2   
207            5      162            104              0        0  37.7   
54             7      150             66             42      342  34.7   
5              5      116             74              0        0  25.6   
579            2      197             70             99        0  34.7   
..           ...      ...            ...            ...      ...   ...   
155            7      152             88             44        0  50.0   
299            8      112             72              0        0  23.6   
643            4       90              0              0        0  28.0   
516            9      145             88             34      165  30.3   
346            1      139             46             19       83  28.7   

     DiabetesPedigreeFunction  Age  Outcome  
362                     0.305   65        0  
207                     0.151   52        1  
54                      0.718   42        0  
5                       0.201   30        0  
579                     0.575   62        1  
..                        ...  ...      ...  
155                     0.337   36        1  
299                     0.840   58        0  
643                     0.610   31        0  
516                     0.771   53        1  
346                     0.654   22        0  

[768 rows x 9 columns]

In [8]:
#scriem coloana care nu dorim sa o afisam
X = df.drop(['Outcome'], axis=1).values
y = df['Outcome'].values

In [9]:
X

array([[5.00e+00, 1.03e+02, 1.08e+02, ..., 3.92e+01, 3.05e-01, 6.50e+01],
       [5.00e+00, 1.62e+02, 1.04e+02, ..., 3.77e+01, 1.51e-01, 5.20e+01],
       [7.00e+00, 1.50e+02, 6.60e+01, ..., 3.47e+01, 7.18e-01, 4.20e+01],
       ...,
       [4.00e+00, 9.00e+01, 0.00e+00, ..., 2.80e+01, 6.10e-01, 3.10e+01],
       [9.00e+00, 1.45e+02, 8.80e+01, ..., 3.03e+01, 7.71e-01, 5.30e+01],
       [1.00e+00, 1.39e+02, 4.60e+01, ..., 2.87e+01, 6.54e-01, 2.20e+01]])

In [10]:
y

array([0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1,
       0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 0, 0, 1, 1,
       0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 0, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1,
       0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0, 0,

In [11]:
# verificam cit de bine lucreaza modelul
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state = 42)

In [12]:
knn = KNeighborsClassifier()

In [14]:
knn.fit(X_train, y_train)

KNeighborsClassifier()

In [15]:
y_pred = knn.predict(X_test)

In [16]:
y_pred

array([0, 0, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 0, 0, 1,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0,
       0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 1,
       0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0], dtype=int64)

In [17]:
accuracy_score(y_pred, y_test)

0.703125

In [18]:
# acuratetea sa o facem mai mare
from sklearn.preprocessing import StandardScaler

In [19]:
std = StandardScaler()
X_train_scaled = std.fit_transform(X_train)

In [20]:
X_test_scaled = std.transform(X_test)

In [21]:
knn.fit(X_train_scaled, y_train)

KNeighborsClassifier()

In [22]:
y_pred = knn.predict(X_test_scaled)

In [23]:
accuracy_score(y_test, y_pred)

0.7291666666666666